package com.neowallet.ai.dto;

/**
 * Classified intent of a user message to the Neo AI Concierge.
 */
public enum IntentType {
    GREETING,
    FINANCIAL_QUERY,
    RECOMMENDATION_REQUEST,
    BUDGET_HELP,
    BILL_HELP,
    SAVINGS_HELP,
    FINANCIAL_HEALTH_QUERY,
    UNKNOWN,
    DENIED_EXECUTION,
    FINANCIAL_OVERVIEW,
    TRANSACTION_ANALYSIS,
    BUDGET_ANALYSIS,
    SAVINGS_ANALYSIS,
    BILL_ANALYSIS,
    FINANCIAL_HEALTH_EXPLANATION,
    GENERAL_FINANCIAL_QUESTION,
    INSUFFICIENT_DATA,
    UNSUPPORTED_REQUEST
}
